FROM maven:3.6.3-jdk-8 as builder

COPY . /usr/src/app
WORKDIR /usr/src/app

RUN mvn package -DskipTests

FROM openjdk:8-jdk-alpine

COPY --from=builder /usr/src/app/target/sample-0.0.1-SNAPSHOT.jar /usr/app/sample-0.0.1-SNAPSHOT.jar

EXPOSE 8080
ENTRYPOINT ["java","-jar","/usr/app/sample-0.0.1-SNAPSHOT.jar"]
