FROM maven:3.6.3-jdk-8 AS build
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN mvn package

FROM openjdk:8-jdk-alpine
COPY --from=build /usr/src/app/target/sample-0.0.1-SNAPSHOT.jar /usr/app/sample-application.jar
WORKDIR /usr/app
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/usr/app/sample-application.jar"]